import 'package:easy_pro/src/datasource/models/invoice.dart';

final List<Map<String, String>> birthRegionList = [
  {'value': 'Selectionner', 'name': "Sélectionner"},
  {'value': 'CENTRE', 'name': "AFANLOUM (Mefou-et-Afamba- CENTRE)"},
  {'value': 'CENTRE', 'name': "AKOEMAN (Nyong-et-So'o - CENTRE)"},
  {'value': 'CENTRE', 'name': "AKONO (Mefou-et-Akono - CENTRE)"},
  {'value': 'CENTRE', 'name': "AKONOLINGA (Nyong-et-Mfoumou - CENTRE)"},
  {'value': 'CENTRE', 'name': "AWAE (Mefou-et-Afamba - CENTRE)"},
  {'value': 'CENTRE', 'name': "AYOS (Nyong-et-Mfoumou - CENTRE)"},
  {'value': 'CENTRE', 'name': "BAFIA (Mbam-et-Inoubou - CENTRE)"},
  {'value': 'CENTRE', 'name': "BIBEY (Haute-Sanaga - CENTRE)"},
  {'value': 'CENTRE', 'name': "BIBEY (Haute-Sanaga - CENTRE)"},
  {'value': 'CENTRE', 'name': "BIKOK (Méfou-et-Akono - CENTRE)"},
  {'value': 'CENTRE', 'name': "BATCHENGA (Lékié - CENTRE)"},
  {'value': 'CENTRE', 'name': "BONDJOCK (Nyong-et-Kéllé - CENTRE)"},
  {'value': 'CENTRE', 'name': "BOTMAKAK (Nyong-et-Kéllé - CENTRE)"},
  {'value': 'CENTRE', 'name': "BOKITO (Mbam-et-Inoubou - CENTRE)"},
  {'value': 'CENTRE', 'name': "BIYOUHA (Nong-et-Kéllé CENTRE)"},
  {'value': 'CENTRE', 'name': "DEUK (Mbam-et-Inoubou - CENTRE)"},
  {'value': 'CENTRE', 'name': "ENDOM (Nyong-et-Mfoumou - CENTRE)"},
  {'value': 'CENTRE', 'name': "ESEKA (Nyong-et-Kéllé - CENTRE)"},
  {'value': 'CENTRE', 'name': "ESSE (Méfou-et-Afamba - CENTRE)"},
  {'value': 'CENTRE', 'name': "EVODOULA (Lékié - CENTRE)"},
  {'value': 'CENTRE', 'name': "ELIG-MFOMO (Lékié - CENTRE)"},
  {'value': 'CENTRE', 'name': "ENDOM (Nyong-et-Mfoumou - CENTRE)"},
  {'value': 'CENTRE', 'name': "ESEKA (Nyong-et-Kéllé - CENTRE)"},
  {'value': 'CENTRE', 'name': "ESSE (Méfou-et-Afamba - CENTRE)"},
  {'value': 'CENTRE', 'name': "EVODOULA (Lékié - CENTRE)"},
  {'value': 'CENTRE', 'name': "YAOUNDE 1er (Mfoundi - CENTRE)"},
  {'value': 'CENTRE', 'name': "YAOUNDE 2ème (Mfoundi - CENTRE)"},
  {'value': 'CENTRE', 'name': "YAOUNDE 3ème (Mfoundi - CENTRE)"},
  {'value': 'CENTRE', 'name': "YAOUNDE 4ème (Mfoundi - CENTRE)"},
  {'value': 'CENTRE', 'name': "YAOUNDE 5ème (Mfoundi - CENTRE)"},
  {'value': 'CENTRE', 'name': "YAOUNDE 6ème (Mfoundi - CENTRE)"},
  {'value': 'CENTRE', 'name': "Yaoundé 7ème (Mfoundi - CENTRE)"},
  {'value': 'CENTRE', 'name': "KIIKI (Mbam-et-Inoubou - CENTRE)"},
  {'value': 'CENTRE', 'name': "KOBDOMBO (Nyong-et-Mfoumou - CENTRE)"},
  {'value': 'CENTRE', 'name': "DIBANG (Nyong-et-Kéllé - CENTRE)"},
  {'value': 'CENTRE', 'name': "EDZENDOUAN (Méfou-et-Afamba - CENTRE)"},
  {'value': 'CENTRE', 'name': "DZENG (Nyong-et-So'o - CENTRE)"},
  {'value': 'CENTRE', 'name': "EBEDA (Lékié - CENTRE)"},
  {'value': 'CENTRE', 'name': "KON-YAMBETTA (Mbam-et-Inoubou - CENTRE)"},
  {'value': 'CENTRE', 'name': "KONTCHA (Faro-et-Déo - CENTRE)"},
  {'value': 'CENTRE', 'name': "MBALMAYO (Nyong-et-So'o - CENTRE)"},
  {'value': 'CENTRE', 'name': "MBANDJOCK (Haute-Sanaga - CENTRE)"},
  {'value': 'CENTRE', 'name': "LEMBE-YEZOUM (Haute-Sanaga - CENTRE)"},
  {'value': 'CENTRE', 'name': "LOBO (Lékié - CENTRE)"},
  {'value': 'CENTRE', 'name': "MAKAK (Nyong-et-Kéllé - CENTRE)"},
  {'value': 'CENTRE', 'name': "MAKENENE (Mbam-et-Inoubou - CENTRE)"},
  {'value': 'CENTRE', 'name': "YOKO (Mbam-et-Kim - CENTRE)"},
  {'value': 'CENTRE', 'name': "YOKO (Mbam-et-Kim - CENTRE)"},
  {'value': 'CENTRE', 'name': "MBANGASSINA (Mbam-et-Kim - CENTRE)"},
  {'value': 'CENTRE', 'name': "MBANKOMO (Méfou-et-Akono - CENTRE)"},
  {'value': 'CENTRE', 'name': "NGOG-MAPUBI (Nyong-et-Kéllé - CENTRE)"},
  {'value': 'CENTRE', 'name': "NGOMEDZAP (Nyong-et-So'o - CENTRE)"},
  {'value': 'CENTRE', 'name': "MONATELE (Lékié - CENTRE)"},
  {'value': 'CENTRE', 'name': "MONATELE (Lékié - CENTRE)"},
  {'value': 'CENTRE', 'name': "NGOUMOU (Méfou-et-Akono - CENTRE)"},
  {'value': 'CENTRE', 'name': "MATOMB (Nyong-et-Kéllé - CENTRE)"},
  {'value': 'CENTRE', 'name': "NITOUKOU (Mbam-et-Inoubou - CENTRE)"},
  {'value': 'CENTRE', 'name': "NKOLAFAMBA (Méfou-et-Afamba - CENTRE)"},
  {'value': 'CENTRE', 'name': "NGUI-BASSAL (Nyong-et-Kéllé - CENTRE)"},
  {'value': 'CENTRE', 'name': "NGORO (Mbam-et-Kim - CENTRE)"},
  {'value': 'CENTRE', 'name': "NKOLMETET (Nyong-et-So'o - CENTRE)"},
  {'value': 'CENTRE', 'name': "NKOTENG (Haute-Sanaga - CENTRE)"},
  {'value': 'CENTRE', 'name': "NGAMBE-TIKAR (Mbam-et-Kim - CENTRE)"},
  {'value': 'CENTRE', 'name': "NSEM (Haute-Sanaga - CENTRE)"},
  {'value': 'CENTRE', 'name': "NTUI (Mbam-et-Kim - CENTRE)"},
  {'value': 'CENTRE', 'name': "OBALA (Lékié - CENTRE)"},
  {'value': 'CENTRE', 'name': "OKOLA (Lékié - CENTRE)"},
  {'value': 'CENTRE', 'name': "OLANGUINA (Méfou-et-Afamba - CENTRE)"},
  {'value': 'CENTRE', 'name': "OMBESSA (Mbam-et-Inoubou CENTRE)"},
  {'value': 'CENTRE', 'name': "SA'A (Lékié - CENTRE)"},
  {'value': 'CENTRE', 'name': "SOA (Méfou-et-Afamba - CENTRE)"},
  {'value': 'CENTRE', 'name': "NANGA-EBOKO (Haute-Sanaga - CENTRE)"},
  {'value': 'CENTRE', 'name': "NDIKINIMEKI (Mbam-et-Inoubou - CENTRE)"},
  {'value': 'CENTRE', 'name': "MENGUEME (Nyong-et-So'o - CENTRE)"},
  {'value': 'CENTRE', 'name': "MESSONDO (Nyong-et-Kéllé - CENTRE)"},
  {'value': 'CENTRE', 'name': "MFOU (Méfou-et-Afamba - CENTRE)"},
  {'value': 'CENTRE', 'name': "MENGANG (Nyong-et-Mfoumou - CENTRE)"},
  {'value': 'CENTRE', 'name': "MINTA (Haute-Sanaga - CENTRE)"},
  {'value': "LITTORAL", 'name': "DOUALA 1er (Wouri - LITTORAL)"},
  {'value': "LITTORAL", 'name': "DOUAL 2ème (Wouri - LITTORAL)"},
  {'value': "LITTORAL", 'name': "DOUALA 3ème (Wouri - LITTORAL)"},
  {'value': "LITTORAL", 'name': "DOUALA 4ème (Wouri - LITTORAL)"},
  {'value': "LITTORAL", 'name': "DOUALA 5ème (Wouri - LITTORAL)"},
  {'value': "LITTORAL", 'name': "BONALEA (Moungo - LITTORAL)"},
  {'value': "LITTORAL", 'name': "DOUALA 6ème (Wouri - LITTORAL)"},
  {'value': "LITTORAL", 'name': "BARE-BAKEM (Moungo - LITTORAL)"},
  {'value': "LITTORAL", 'name': "DIZANGUE (Sanaga-Maritime - LITTORAL)"},
  {'value': "LITTORAL", 'name': "DIBAMBA (Sanaga-Maritime - LITTORAL)"},
  {'value': "LITTORAL", 'name': "DIBOMBARI (Moungo - LITTORAL)"},
  {'value': "LITTORAL", 'name': "DIBOMBARI (Moungo - LITTORAL)"},
  {'value': "LITTORAL", 'name': "EBONE (Moungo - LITTORAL)"},
  {'value': "LITTORAL", 'name': "EDEA 1er (Sanaga-Maritime - LITTORAL)"},
  {'value': "LITTORAL", 'name': "EDEA 2ème (Sanaga-Maritime - LITTORAL)"},
  {'value': "LITTORAL", 'name': "LOUM (Moungo - LITTORAL)"},
  {'value': "LITTORAL", 'name': "MANDJO (Moungo - LITTORAL)"},
  {'value': "LITTORAL", 'name': "MANDJO (Moungo - LITTORAL)"},
  {
    'value': "LITTORAL",
    'name': "MASSOCK-SONGLOULOU (Sanaga-Maritime - LITTORAL)"
  },
  {'value': "LITTORAL", 'name': "MBANGA (Moungo - LITTORAL)"},
  {'value': "LITTORAL", 'name': "MELONG (Moungo - LITTORAL)"},
  {'value': "LITTORAL", 'name': "MOMBO (Moungo - LITTORAL)"},
  {'value': "LITTORAL", 'name': "MOUANKO (Sanaga-Maritime - LITTORAL)"},
  {'value': "LITTORAL", 'name': "NGAMBE (Sanaga-Maritime - LITTORAL)"},
  {'value': "LITTORAL", 'name': "NKONDJOCK (Nkam - LITTORAL)"},
  {'value': "LITTORAL", 'name': "NKONDJOCK (Nkam - LITTORAL)"},
  {'value': "LITTORAL", 'name': "NKONGSAMBA 1er (Moungo - LITTORAL)"},
  {'value': "LITTORAL", 'name': "NKONGSAMBA 2ème (Moungo - LITTORAL)"},
  {'value': "LITTORAL", 'name': "NKONGSAMBA 3ème (Moungo - LITTORAL)"},
  {'value': "LITTORAL", 'name': "NDOBIAN (Nkam - LITTORAL)"},
  {'value': "LITTORAL", 'name': "NDOM (Sanaga-Maritime - LITTORAL)"},
  {'value': "LITTORAL", 'name': "POUMA (Sanaga-Maritime Littoral)"},
  {'value': "LITTORAL", 'name': "NGWEI (Sanaga-Maritime - LITTORAL)"},
  {'value': "LITTORAL", 'name': "PENDJA (Moungo - LITTORAL)"},
  {'value': "LITTORAL", 'name': "NYANON (Sanaga-Maritime - LITTORAL)"},
  {'value': "LITTORAL", 'name': "YABASSI (Nkam - LITTORAL)"},
  {'value': "LITTORAL", 'name': "YINGUI (Nkam -- LITTORAL)"},
  {'value': "OUEST", 'name': "BAFOUSSAM 1er (Mifi - OUEST)"},
  {'value': "OUEST", 'name': "BAFOUSSAM 2ème (Mifi - OUEST)"},
  {'value': "OUEST", "name": "BAFOUSSAM 3ème (Mifi - OUEST"},
  {'value': "BAFUT (Mezam - NORTH-WEST)", 'name': "ANDEK (Momo - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "BALI (Mezam - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "BALIKUMBAT (Ngo-Ketundjia - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "BAMENDA 1er (Mezam - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "BAMENDA 2ème (Mezam - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "BAMENDA 3ème (Mezam - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "BATIBO (Momo - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "BELO (Boyo - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "BENAKUMA (Menchum - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "ELAK-OKU (Bui - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "FONFUKA (Boyo - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "FONFUKA (Boyo - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "JAKIRI (Bui - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "NJIKWA (Momo - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "NJINIKOM (Boyo - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "NKAMBE (Donga-Mantung - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "NKOR (Bui - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "NKUM (Bui - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "NWA (Donga-Mantung - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "NDU (Donga-Mantung) - NORTH-WEST"},
  {'value': "NORTH-WEST", 'name': "MBENGWI (Momo - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "NDOP (Ngo-ketundjia - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "KUMBO (Bui - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "MBIAME (Bui - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "MISAJE (Donga-Mantung - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "SANTA (Mezam - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "ZHOA (Menchum - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "WUM (Menchum - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "WIDIKUM-BOFFE (Momo - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "TUBAH (Mezam - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "FUNDONG (Boyo - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "FURU-AWA (Menchum - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "FUNDONG (Boyo - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "FURU-AWA (Menchum - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "AKO (Donga-Mantung - NORTH-WEST)"},
  {'value': "NORTH-WEST", 'name': "BABESSI (Ngo-Ketundjia - NORTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "EKONDO-TITI (Ndian - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "EYUMODJOCK (Manyu - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "AKWAYA (Manyu - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "ALOU (Lebialem - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "BAMUSSO (Ndian - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "BANGUEM (Koupé-Manengouba - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "DIKOME-BALUE (Ndiang - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "EYUMODJOCK (Manyu - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "KOMBO-ABEDIMO (Ndian - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "KOMBO-IDINTI (Ndian - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "IDABATO (Ndian - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "ISANGUELE (Ndian - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "KONYE (Meme SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "BUEA (Fako - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "KUMBA 1er (Meme - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "KUMBA 2ème (Meme - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "KUMBA 3ème (Meme - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "LIMBE 1er (Fako -SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "LIMBE 2è (Fako - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "KUMBA 2ème (Meme - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "MAMFE (Manyu - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "MBONGE (Meme - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "MBONGE (Meme - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "MENJI (Lebialem - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "MUNDEMBA (Ndian - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "LIMBE 3è (Fako - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "TIKO (Fako - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "TOKO (Ndian - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "NGUTI (Koupé-Manengouba - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "WEST COAST (Fako - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "UPPER BAYANG (Manyu SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "WABANE (Lebialem - SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "TOMBEL (Koupé-Manengouba SOUTH-WEST)"},
  {'value': "SOUTH-WEST", 'name': "TOMBEL (Koupé-Manengouba SOUTH-WEST)"},
  {'value': "EXTREME-NORD", 'name': "GAZAWA (Diamaré - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "GOBO (Mayo-Danay - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "DZIGUILAO (Mayo-Kani - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "GOULFEY (Logone-et-Chari EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "FOTOKOL (Logone-et-Chari - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "GUEME (Mayo-Danay - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "GUERE (Mayo-Danay - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "GUIDIGUIS (Mayo-Kani - EXTREME-NORD)"},
  {
    'value': "EXTREME-NORD",
    'name': "HILE-ALIFA (Logone-et-Chari - EXTREME-NORD)"
  },
  {'value': "EXTREME-NORD", 'name': "HINA (Mayo-Tsanaga - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "KAELE (Mayo-Kani - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "KAI-KAI (Mayo-Danay - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "KALFOU (Mayo-Danay - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "KAR-HAY (Mayo-Danay - EXTREME-NORD)"},
  {
    'value': "EXTREME-NORD",
    'name': "KOUSSERI (Logone-et-Chari - EXTREME-NORD)"
  },
  {'value': "EXTREME-NORD", 'name': "KOLOFATA (Mayo-Sava - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "KOZA (Mayo-Tsanaga - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "MAGA (Mayo-Danay - EXTREME-NORD)"},
  {
    'value': "EXTREME-NORD",
    'name': "LOGONNE-BIRNI (Logone-et-Chari - EXTREME-NORD)"
  },
  {'value': "EXTREME-NORD", 'name': "MAKARY (Logone-et-Chari - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "MAROUA 1er (Diamaré - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "MAROUA 2ème (Diamaré - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "MAROUA 3ème (Diamaré - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "MORA (Mayo-Sava - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "MOULVOUDAYE (Mayo-Kani - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "MOUTOURWA (Mayo-Kani - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "MOZOGO (Mayo-Tsanaga - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "MOGODE (Mayo-Tsanaga - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "MOKOLO (Mayo-Tsanaga - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "NDOUKOULA (Diamaré - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "MINDIF (Mayo-Kani - EXTREME-NORD)"},
  {
    'value': "EXTREME-NORD",
    'name': "SOULEDE-ROUA (Mayo-Tsanaga - EXTREME-NORD)"
  },
  {'value': "EXTREME-NORD", 'name': "TCHATI-BALI (Mayo-Danay - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "PETTE (Diamaré - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "TOKOMBERE (Mayo-Sava - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "WAZA (Logone-et-Chari - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "TOULOUM (Mayo-Kani - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "WINA (Mayo-Danay EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "YAGOUA (Mayo-Danay - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "ZINA (Logone-et-Chari - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "DARGALA (Diamaré - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "DARAK (Diamaré - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "DATCHEKA (Mayo-Danay - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "BOGO (Diamaré - EXTREME- NORD)"},
  {'value': "EXTREME-NORD", 'name': "BOURRHA (Mayo-Tsanaga - EXTREME-NORD)"},
  {'value': "EXTREME-NORD", 'name': "MERI (Diamaré - EXTREME-NORD)"},
  {
    'value': "EXTREME-NORD",
    'name': "BLANGOUA (Logone-et-Chari - EXTREME-NORD)"
  },
  {'value': "NORD", 'name': "DEMBO (Bénoué - NORD)"},
  {'value': "NORD", 'name': "BIBEMI (Bénoué - NORD)"},
  {'value': "NORD", 'name': "BEKA (Faro - NORD)"},
  {'value': "NORD", 'name': "BARNDAKE (Bénoué - NORD)"},
  {'value': "NORD", 'name': "BASHEO (Bénoué - NORD)"},
  {'value': "NORD", 'name': "GAROUA 1er (Bénoué - NORD)"},
  {'value': "NORD", 'name': "GAROUA 2ème (Bénoué - NORD)"},
  {'value': "NORD", 'name': "GAROUA 3ème (Bénoué - NORD)"},
  {'value': "NORD", 'name': "GASHIGA (Bénoué - NORD)"},
  {'value': "NORD", 'name': "LAGDO (Bénoué - NORD)"},
  {'value': "NORD", 'name': "FIGUIL (Mayo-Louuti - NORD)"},
  {'value': "NORD", 'name': "GUIDER (Mayo-Louti - NORD)"},
  {'value': "NORD", 'name': "MAYO-OULO (Mayo-Louti - NORD)"},
  {'value': "NORD", 'name': "MADINGRING (Mayo-Rey - NORD)"},
  {'value': "NORD", 'name': "NGONG (Bénoué - NORD)"},
  {'value': "NORD", 'name': "PITOA (Bénoué - NORD)"},
  {'value': "NORD", 'name': "TCHOLLIRE (Mayo-Rey - NORD)"},
  {'value': "NORD", 'name': "POLI (Faro - NORD)"},
  {'value': "NORD", 'name': "REY-BOUBA (Mayo-Rey - NORD)"},
  {'value': "NORD", 'name': "TOUBORO (Mayo-Rey - NORD)"},
  {'value': "NORD", 'name': "TOUROUA (Bénoué - NORD)"},
  {'value': "SUD", 'name': "BIPINDI (Océan - SUD)"},
  {'value': "SUD", 'name': "BIWONG-BANE (Mvila - SUD)"},
  {'value': "SUD", 'name': "BIWONG-BULU (Mvila - SUD)"},
  {'value': "SUD", 'name': "CAMPO (Océan - SUD)"},
  {'value': "SUD", 'name': "BENGBIS (Dja-et-Lobo - SUD)"},
  {'value': "SUD", 'name': "EBOLOWA 1er (Mvila - SUD)"},
  {'value': "SUD", 'name': "EBOLOWA 2ème (Mvila - SUD)"},
  {'value': "SUD", 'name': "EFOULAN (Mvila - SUD)"},
  {'value': "SUD", 'name': "DJOUM (Dja-et-Lobo - SUD)"},
  {'value': "SUD", 'name': "KRIBI 1er (Océan - SUD)"},
  {'value': "SUD", 'name': "KRIBI 2ème (Océan - SUD)"},
  {'value': "SUD", 'name': "KYE-OSSI (Vallée-du-Ntem - SUD)"},
  {'value': "SUD", 'name': "LOKOUNDJE (Océan - SUD)"},
  {'value': "SUD", 'name': "LOLODORF (Océan -SUD)"},
  {'value': "SUD", 'name': "MA'AN (Vallée-du-Ntem - SUD)"},
  {'value': "SUD", 'name': "MEYOMESSALA (Dja-et-Lobo - SUD)"},
  {'value': "SUD", 'name': "MEYOMESSI (Dja-et-Lobo - SUD)"},
  {'value': "SUD", 'name': "MINTOM (Dja-et-Lobo - SUD)"},
  {'value': "SUD", 'name': "MENGONG (Mvila - SUD)"},
  {'value': "SUD", 'name': "MVANGAN (Mvila - SUD)"},
  {'value': "SUD", 'name': "MVENGUE (Océan - SUD)"},
  {'value': "SUD", 'name': "NGOULEMAKONG (Mvila - SUD)"},
  {'value': "SUD", 'name': "OLAMZE (Vallée-du-Ntem SUD)"},
  {'value': "SUD", 'name': "OVENG (Dja-et-Lobo - SUD)"},
  {'value': "SUD", 'name': "SANGMELIMA (Dja-et-Lobo - SUD)"},
  {'value': "SUD", 'name': "ZOETELE (Dja-et-Lobo - SUD)"},
  {'value': "SUD", 'name': "NIETE (Océan - SUD)"},
  {'value': "SUD", 'name': "AKOM II (Océan - SUD)"},
  {'value': "SUD", 'name': "AMBAM (Vallée-du-Ntem - SUD)"},
  {'value': "EST", 'name': "ABONG-MBANG (Haut-Nyong - EST)"},
  {'value': "EST", 'name': "ANGOSSASS (Haut-Nyong - EST)"},
  {'value': "EST", 'name': "ATOK (Haut-Nyong - EST)"},
  {'value': "EST", 'name': "BELABO (Lom-et-Djérem - EST)"},
  {'value': "EST", 'name': "BERTOUA 1er (Lom-et-Djérem - EST)"},
  {'value': "EST", 'name': "BERTOUA 2ème (Lom-et-Djérem - EST)"},
  {'value': "EST", 'name': "BETARE-OYA (Lom-et-Djérem - EST)"},
  {'value': "EST", 'name': "BATOURI (Kadey - EST)"},
  {'value': "EST", 'name': "DIANG (Lom-et-Djérem - EST)"},
  {'value': "EST", 'name': "DIMAKO (Haut-Nyong - EST)"},
  {'value': "EST", 'name': "DOUMAINTANG (Haut-Nyong - EST)"},
  {'value': "EST", 'name': "DOUME (Haut-Nyong - EST)"},
  {'value': "EST", 'name': "GARI-GOMBO (Boumba-et-Ngoko - EST)"},
  {'value': "EST", 'name': "LOMIE (Haut-Nyong - EST)"},
  {'value': "EST", 'name': "MANDJOU (Lom-et-Djérem - EST)"},
  {'value': "EST", 'name': "MBANG (Kadey - EST)"},
  {'value': "EST", 'name': "MBOMA (Haut-Nyong - EST)"},
  {'value': "EST", 'name': "NGOURA (Lom-et-Djérem - EST)"},
  {'value': "EST", 'name': "NGOYLA (Haut-Nyong - EST)"},
  {'value': "EST", 'name': "NGUELEBOK (Kadey - EST)"},
  {'value': "EST", 'name': "OULI( Kadey - EST)"},
  {'value': "EST", 'name': "SALAPOUMBE (Boumba-et-Ngoko - EST)"},
  {'value': "EST", 'name': "SOMALOMO (Haut-Nyong - EST)"},
  {'value': "EST", 'name': "YOKADOUMA (Boumba-et-Ngoko - EST)"},
  {'value': "EST", 'name': "NGUELEMENDOUKA (Haut-Nyong - EST)"},
  {'value': "EST", 'name': "MESSAMENA (Haut-Nyong - EST)"},
  {'value': "EST", 'name': "MESSOK (Haut-Nyong - EST)"},
  {'value': "EST", 'name': "MOLOUNDOU (Boumba-et-Ngoko EST)"},
  {'value': "EST", 'name': "MINDOUROU (Haut-Nyong - EST)"},
  {'value': "EST", 'name': "NDELELE (Kadey - EST)"},
  {'value': "EST", 'name': "KENTZOU (Kadey - EST)"},
  {'value': "EST", 'name': "KETTE (Kadey - EST)"},
  {'value': "EST", 'name': "GARI-GOMBO (Boumba-et-Ngoko - EST)"},
  {'value': "EST", 'name': "GAROUA-BOULAÏ (Lom-et-Djérem - EST)"},
  {'value': "ADAMAOUA", 'name': "BANYO (Mayo-Banyo - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "BANKIM (Mayo-Banyo - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "GALIM-TIGNERE (Faro-et-Déo - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "BELEL (Vina - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "GALIM-TIGNERE (Faro-et-Déo - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "DIR (Mbéré - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "DJOHONG (Mbéré - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "MEINGANGA (Mbéré - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "NGANHA (Vina - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "NGAOUÏ (Mbéré - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "NGAOUNDAL (Djérem - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "NGAOUNDERE 1er (Vina - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "NGAOUNDERE 1er (Vina - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "NGAOUNDERE 2ème (Vina - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "NGAOUNDERE 3ème (Vina - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "MAYO-BALEO (Faro-et-Déo - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "MAYO-DARLE (Mayo-Banyo - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "MBE (Vina - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "TIBATI (Djérem - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "TIGNERE (Faro-e-tDéo - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "NYAMBAKA (Vina - ADAMAOUA)"},
  {'value': "ADAMAOUA", 'name': "MARTAP (Vina - ADAMAOUA)"},
];

final List<Map<String, String>> birthAdamaoua = [];

final List<String> birthList = [
  "ABONG-MBANG (Haut-Nyong - EST)",
  "AFANLOUM (Mefou-et-Afamba - CENTRE)",
  "AKO (Donga-Mantung - NORTH-WEST)",
  "AKOEMAN (Nyong-et-So’o - CENTRE)",
  "AKOM 2 (Océan - SUD)",
  "AKONO (Mefou-et-Akono - CENTRE)",
  "AKONOLINGA (Nyong-et-Mfoumou - CENTRE)",
  "AKWAYA (Manyu - SOUTH-WEST)",
  "ALOU (Lebialem - SOUTH-WEST)",
  "AMBAM (Vallée-du-Ntem - SUD)",
  "ANDEK (Momo - NORTH-WEST)",
  "ANGOSSASS (Haut-Nyong - EST)",
  "ATOK (Haut-Nyong - EST)",
  "AWAE (Mefou-et-Afamba - CENTRE)",
  "AYOS (Nyong-et-Mfoumou - CENTRE)",
  "BABADJOU (Bamboutos - OUEST)",
  "BABESSI (Ngo-Ketundjia - NORTH-WEST)",
  "BAFANG (Haut-Nkam - OUEST)",
  "BAFIA (Mbam-et-Inoubou - CENTRE)",
  "BAFOUSSAM 1er (Mifi - OUEST)",
  "BAFOUSSAM 2ème (Mifi - OUEST)",
  "BAFOUSSAM 3ème (Mifi - OUEST)",
  "BAFUT (Mezam - NORTH-WEST)",
  "BAHAM (Hauts-Plateaux - OUEST)",
  "BAKOU (Haut-Nkam - OUEST)",
  "BALI (Mezam - NORTH-WEST)",
  "BALIKUMBAT (Ngo-Ketundjia - NORTH-WEST)",
  "BAMENDA 1er (Mezam - NORTH-WEST)",
  "BAMENDA 2ème (Mezam - NORTH-WEST)",
  "BAMENDA 3ème (Mezam - NORTH-WEST)",
  "BAMENDJOU (Hauts-Plateaux - OUEST)",
  "BAMUSSO (Ndian - SOUTH-WEST)",
  "BANA (Haut-Nkam - OUEST)",
  "BANDJA (Haut-Nkam - OUEST)",
  "BANDJOUN (Koung-Khi - OUEST) ",
  "BANGANGTE (Ndé - OUEST) ",
  "BANGEM (Koupé-Manengouba - SOUTH-WEST) ",
  "BANKA (Haut-Nkam - OUEST) ",
  "BANGOU (Hauts-Plateaux - OUEST)",
  "BANGOURAIN (Noun - OUEST)",
  "BANGUEM (Koupé-Manengouba - SOUTH-WEST)",
  "BANKIM (Mayo-Banyo – ADAMAOUA)",
  "BANWA (Haut-Nkam - OUEST)",
  "BANYO (Mayo-Banyo – ADAMAOUA)",
  "BARE-BAKEM (Moungo - LITTORAL) ",
  "BARNDAKE (Bénoué - NORD)",
  "BASHEO (Bénoué - NORD)",
  "BASSAMBA (Ndé - OUEST)",
  "BATCHAM (Bamboutos - OUEST)",
  "BATCHENGA (Lékié - CENTRE)",
  "BATIBO (Momo - NORTH-WEST)",
  "BATIE (Hauts-Plateaux - OUEST)",
  "BATOURI (Kadey - EST)",
  "BAYANGAM (Koung-Khi - OUEST)",
  "BAZOU (Ndé - OUEST)",
  "BEKA (Faro - NORD)",
  "BELABO (Lom-et-Djérem - EST)",
  "BELEL (Vina – ADAMAOUA)",
  "BELO (Boyo - NORTH-WEST)",
  "BENAKUMA (Menchum - NORTH-WEST)",
  "BENGBIS (Dja-et-Lobo - SUD)",
  "BERTOUA 1er (Lom-et-Djérem - EST)",
  "BERTOUA 2ème (Lom-et-Djérem - EST)",
  "BETARE-OYA (Lom-et-Djérem - EST)",
  "BIBEMI (Bénoué - NORD)",
  "BIBEY (Haute-Sanaga - CENTRE)",
  "BIKOK (Mefou-et-Akono - CENTRE)",
  "BIPINDI (Océan - SUD)",
  "BIWONG-BANE (Mvila - SUD)",
  "BIWONG-BULU (Mvila - SUD)",
  "BIYOUHA (Nyong-et-Kéllé - CENTRE)",
  "BLANGOUA (Logone-et-Chari - EXTREME-NORD)",
  "BOGO (Diamaré - EXTREME-NORD)",
  "BOKITO (Mbam-et-Inoubou - CENTRE)",
  "BONALEA (Moungo - LITTORAL)",
  "BONDJOCK (Nyong-et-Kéllé - CENTRE)",
  "BOTMAKAK (Nyong-et-Kéllé - CENTRE)",
  "BOURRHA (Mayo-Tsanaga - EXTREME-NORD)",
  "BUEA (Fako - SOUTH-WEST)",
  "CAMPO (Océan - SUD)",
  "DARGALA (Diamaré - EXTREME-NORD)",
  "DARAK (Logone-et-Chari - EXTREME-NORD)",
  "DATCHEKA (Mayo-Danay - EXTREME-NORD)",
  "DEMBO (Bénoué - NORD)",
  "DEMDENG (Koung-Khi - OUEST)",
  "DEUK (Mbam-et-Inoubou - CENTRE)",
  "DIANG (Lom-et-Djérem - EST)",
  "DIBAMBA (Sanaga-Maritime - LITTORAL)",
  "DIBANG (Nyong-et-Kéllé - CENTRE)",
  "DIBOMBARI (Moungo - LITTORAL)",
  "DIKOME-BALUE (Ndian - SOUTH-WEST)",
  'DIMAKO (Haut-Nyong - EST)',
  "DIR (Mbéré - ADAMAOUA)",
  "DIZANGUE (Sanaga-Maritime - LITTORAL)",
  "DJOHONG (Mbéré - ADAMAOUA)",
  "DJOUM (Dja-et-Lobo - SUD)",
  "DOUALA 1er (Wouri - LITTORAL)",
  "DOUALA 2ème (Wouri - LITTORAL)",
  "DOUALA 3ème (Wouri - LITTORAL)",
  "DOUALA 4ème (Wouri - LITTORAL)",
  "DOUALA 5ème (Wouri - LITTORAL)",
  "DOUALA 6ème (Wouri -  LITTORAL)",
  "DOUMAINTANG (Haut-Nyong - EST)",
  "DOUME (Haut-Nyong - EST)",
  "DSCHANG (Menoua - OUEST)",
  "DZENG (Nyong-et-So’o - CENTRE)",
  "DZIGUILAO (Mayo-Kani - EXTREME-NORD)",
  "EBEBDA (Lékié - CENTRE)",
  "EBOLOWA 1er (Mvila - SUD)",
  "EBOLOWA 2ème (Mvila - SUD)",
  "EBONE (Moungo - LITTORAL)",
  "EDEA 1er (Sanaga-Maritime - LITTORAL)",
  "EDEA 2ème (Sanaga-Maritime - LITTORAL)",
  "EDZENDOUAN (Mefou-et-Afamba - CENTRE)",
  "EFOULAN (Mvila - SUD)",
  "EKONDO-TITI (Ndian - SOUTH-WEST)",
  "ELAK-OKU (OKU) (Bui - NORTH-WEST)",
  "ELIG-MFOMO (Lékié - CENTRE)",
  "ENDOM (Nyong-et-Mfoumou - CENTRE)",
  "ESEKA (Nyong-et-Kéllé - CENTRE)",
  "ESSE (Mefou-et-Afamba - CENTRE)",
  "EVODOULA (Lékié - CENTRE)",
  "EYUMODJOCK (Manyu - SOUTH-WEST)",
  "FIGUIL (Mayo-Louti - NORD)",
  "FOKOUE (Menoua - OUEST)",
  "FONFUKA (Boyo - NORTH-WEST)",
  "FONGO-TONGO (Menoua - OUEST)",
  "FOTOKOL (Logone-et-Chari - EXTREME-NORD)",
  "FOUMBAN (Noun - OUEST)",
  "FOUMBOT (Noun - OUEST)",
  "FUNDONG (Boyo - NORTH-WEST)",
  "FURU-AWA (Menchum - NORTH-WEST)",
  "GALIM (Bamboutos - OUEST)",
  "GALIM-TIGNERE (Faro-et-Déo - ADAMAOUA)",
  "GARI-GOMBO (Boumba-et-Ngoko - EST)",
  "GAROUA 1er (Bénoué - NORD)",
  "GAROUA 2ème (Bénoué - NORD)",
  "GAROUA 3ème (Bénoué - NORD)",
  "GAROUA-BOULAÏ (Lom-et-Djerem - EST)",
  "GASHIGA (Bénoué - NORD)",
  "GAZAWA (Diamaré - EXTREME-NORD)",
  "GOBO (Mayo-Danay - EXTREME-NORD)",
  "GOULFEY ( Logone-et-Chari - EXTREME-NORD)",
  "GUEME (Mayo-Danay - EXTREME-NORD)",
  "GUERE (Mayo-Danay - EXTREME-NORD)",
  "GUIDER (Mayo-Louti - NORD)",
  "GUIDIGUIS (Mayo-Kani - EXTREME-NORD)",
  "HILE-HALIFA (Logone-et-Chari - EXTREME-NORD)",
  "HINA (Mayo-Tsanaga - EXTREME-NORD)",
  "IDABATO (Ndian - SOUTH-WEST)",
  "ISANGUELE (Ndian - SOUTH-WEST)",
  "JAKIRI (Bui - NORTH-WEST)",
  "KAELE (Mayo-Kani - EXTREME-NORD)",
  "KAI-KAI (Mayo-Danay - EXTREME-NORD)",
  "KALFOU (Mayo-Danay - EXTREME-NORD)",
  "KAR-HAY (Mayo-Danay - EXTREME-NORD)",
  "KEKEM (Haut-Nkam - OUEST)",
  "KENTZOU (Kadey - EST)",
  "KETTE (Kadey - EST)",
  "KIE-OSSI (Vallée-du-Ntem - SUD)",
  "Kiiki (Mbam-et-Inoubou - CENTRE)",
  "KOBDOMBO (Nyong-et-Mfoumou - CENTRE)",
  "KOLOFATA (Mayo-Sava - EXTREME-NORD)",
  "KOMBO-ABEDIMO (Ndian - SOUTH-WEST)",
  "KOMBO-IDINTI (Ndian - SOUTH-WEST)",
  "KON-YAMBETTA (Mbam-et-Inoubou - CENTRE)",
  "KONTCHA (Faro-et-Déo - ADAMAOUA)",
  "KONYE (Meme - SOUTH-WEST)",
  "KOUOPTAMO (Noun - OUEST)",
  "KOUSSERI (Logone-et-Chari - EXTREME-NORD)",
  "KOUTABA (Noun - OUEST)",
  "KOZA (Mayo-Tsanaga - EXTREME-NORD)",
  "KRIBI 1er (Océan - SUD)",
  "KRIBI 2ème (Océan - SUD)",
  "KUMBA 1er (Meme - SOUTH-WEST)",
  "KUMBA 2ème (Meme - SOUTH-WEST)",
  "KUMBA 3ème (Meme - SOUTH-WEST)",
  "KUMBO (Bui - NORTH-WEST)",
  "LAGDO (Bénoué - NORD)",
  "LEMBE-YEZOUM (Haute-Sanaga - CENTRE)",
  "LIMBE 1er (Fako - SOUTH-WEST)",
  "LIMBE 2ème (Fako - SOUTH-WEST)",
  "LIMBE 3ème (Fako - SOUTH-WEST)",
  "LOBO (Lékié - CENTRE)",
  "LOGONE-BIRNI (Logone-et-Chari - EXTREME-NORD)",
  "LOKOUNDJE (Océan - SUD)",
  "LOLODORF (Océan - SUD) ",
  "LOMIE (Haut-Nyong - EST)",
  "LOUM (Moungo - LITTORAL)",
  "MA’AN (Vallée-du-Ntem - SUD)",
  "MADINGRING (Mayo-Rey - NORD)",
  "MAGA (Mayo-Danay - EXTREME-NORD)",
  "MAGBA (Noun - OUEST)",
  "MAKAK (Nyong-et-Kéllé - CENTRE)",
  "MAKARY (Logone-et-Chari - EXTREME-NORD)",
  "MAKENENE (Mbam-et-Inoubou - CENTRE)",
  "MALENTOUEN (Noun - OUEST)",
  "MAMFE CENTRAL (MAMFE) (Manyu - SOUTH-WEST)",
  "MANDJOU (Lom-et-Djerem - EST)",
  "MANJO (Moungo - LITTORAL)",
  "MAROUA 1er(Diamaré - EXTREME-NORD)",
  "MAROUA 2ème (Diamaré - EXTREME-NORD)",
  "MAROUA 3ème (Diamaré - EXTREME-NORD)",
  "MARTAP (Vina - ADAMAOUA)",
  "MASSANGAM (Noun - OUEST)",
  "MASSOCK-SONGLOULOU (Sanaga-Maritime - LITTORAL)",
  "MATOMB (Nyong-et-Kéllé - CENTRE)",
  "MAYO-BALEO (Faro-et-Déo - ADAMAOUA)",
  "MAYO-DARLE (Mayo-Banyo – ADAMAOUA)",
  "MAYO-OULO (Mayo-Louti - NORD)",
  "MBALMAYO (Nyong-et-So’o - CENTRE)",
  "MBANDJOCK (Haute-Sanaga - CENTRE)",
  "MBANG (Kadey - EST)",
  "MBANGA (Moungo - LITTORAL)",
  "MBANGASSINA (Mbam-et-Kim - CENTRE)",
  "MBANKOMO (Mefou-et-Akono - CENTRE) ",
  "MBE (Vina - ADAMAOUA)",
  "MBENGWI (Momo - NORTH-WEST)",
  "MBOMA (Haut-Nyong - EST)",
  "MBONGUE (Meme - SOUTH-WEST)",
  "MBOUDA (Bamboutos - OUEST)",
  "MBVEN (MBIAME) (Bui - NORTH-WEST)",
  "MEIGANGA (Mbéré - ADAMAOUA)",
  "MELONG (Moungo - LITTORAL)",
  "MENDJI (Lebialem - SOUTH-WEST)",
  "MENGANG (Nyong-et-Mfoumou - CENTRE)",
  "MENGONG (Mvila - SUD)",
  "MENGUEME (Nyong-et-So’o - CENTRE)",
  "MERI (Diamaré - EXTREME-NORD)",
  "MESSAMENA (Haut-Nyong - EST)",
  "MESSOK (Haut-Nyong - EST)",
  "MESSONDO (Nyong-et-Kéllé - CENTRE)",
  "MEYOMESSALA (Dja-et-Lobo - SUD)",
  "MEYOMESSI (Dja-et-Lobo - SUD)",
  "MFOU (Mefou-et-Afamba - CENTRE)",
  "MINDIF (Mayo-Kani - EXTREME-NORD)",
  "MINDOUROU (Haut-Nyong - EST)",
  "MINTA (Haute-Sanaga - CENTRE)",
  "MINTOM (Dja-et-Lobo - SUD)",
  "MISAJE (Donga-Mantung - NORTH-WEST)",
  "MOGODE (Mayo-Tsanaga - EXTREME-NORD)",
  "MOKOLO (Mayo-Tsanaga - EXTREME-NORD)",
  "MOLOUNDOU (Boumba-et-Ngoko - EST)",
  "MOMBO (Moungo - LITTORAL)",
  "MONATELE (Lékié - CENTRE)",
  "MORA (Mayo-Sava - EXTREME-NORD)",
  "MOTOURWA (Mayo-Kani - EXTREME-NORD)",
  "MOUANKO (Sanaga-Maritime - LITTORAL)",
  "MOULVOUDAYE (Mayo-Kani - EXTREME-NORD)",
  "MOZOGO (Mayo-Tsanaga - EXTREME-NORD)",
  "MUNDEMBA (Ndian - SOUTH-WEST)",
  "MUYUKA (Fako - SOUTH-WEST)",
  "MVANGAN (Mvila - SUD)",
  "MVENGUE (Océan - SUD)",
  "NANGA EBOKO (Haute-Sanaga - CENTRE)",
  "NDELELE (Kadey - EST)",
  "NDIKINIMEKI (Mbam-et-Inoubou - CENTRE)",
  "NDJIMOM (Noun - OUEST)",
  "NDJINIKOM (Boyo - NORTH-WEST)",
  "NDJOMBE-PENDJA (PENDJA) (MOUNGO - LITTORAL)",
  "NDOM (Sanaga-Maritime - LITTORAL)",
  "NDOP (Ngo-Ketundjia - NORTH-WEST)",
  "NDOUKOULA (Diamaré - EXTREME-NORD)",
  "NDU (Donga-Mantung - NORTH-WEST)",
  "NGAMBE (Sanaga-Maritime - LITTORAL)",
  "NGAMBE-TIKAR (Mbam-et-Kim - CENTRE)",
  "NGANHA (Vina - ADAMAOUA)",
  "NGAOUI (Mbéré - ADAMAOUA)",
  "NGAOUNDAL (Djerem - ADAMAOUA)",
  "NGAOUNDERE 1er (Vina - ADAMAOUA)",
  "NGAOUNDERE 2ème (Vina - ADAMAOUA)",
  "NGAOUNDERE 3ème (Vina - ADAMAOUA)",
  "NGOG-MAPUBI (Nyong-et-Kéllé - CENTRE)",
  "NGOMEDZAP (Nyong-et-So’o - CENTRE)",
  "NGONG (Bénoué - NORD)",
  "NGORO (Mbam-et-Kim - CENTRE)",
  "NGOULEMAKONG (Mvila - SUD)",
  "NGOUMOU (Mefou-et-Akono - CENTRE)",
  "NGOURA (Lom-et-Djérem - EST)",
  "NGOYLA (Haut-Nyong - EST)",
  "NGUELEBOK (Kadey - EST)",
  "NGUELEMENDOUKA (Haut-Nyong - EST)",
  "NGUI-BASSAL (Nyong-et-Kéllé - CENTRE)",
  "NGUTI (Koupé-Manengouba - SOUTH-WEST)",
  "NGWEI (Sanaga-Maritime - LITTORAL)",
  "NIETE (Océan - SUD)",
  "NITOUKOU (Mbam et Inoubou - CENTRE)",
  "NJIKWA (Momo - NORTH-WEST)",
  "NKAMBE (Donga-Mantung - NORTH-WEST)",
  "NKOLAFAMBA (Mefou-et-Afamba - CENTRE)",
  "NKOLMETET (Nyong-et-So’o - CENTRE)",
  "NKONDJOCK (Nkam - LITTORAL)",
  "NKONGSAMBA 1er (Moungo - LITTORAL)",
  "NKONGSAMBA 2ème (Moungo - LITTORAL)",
  "NKONGSAMBA 3ème (Moungo - LITTORAL)",
  "NKONG-ZEM (Menoua - OUEST)",
  "NKOTENG (HauteSanaga - CENTRE)",
  "NKUM (Bui - NORTH-WEST)",
  "NONI(NKOR) (Bui - NORTH-WEST)",
  "NORD-MAKOMBE (Nkam - LITTORAL)",
  "NSEM (Haute-Sanaga - CENTRE) ",
  "NTUI (Mbam-et-Kim - CENTRE)",
  "NWA (Donga-Mantung  - NORTH-WEST)",
  "NYAMBAKA (Vina - ADAMAOUA)",
  "NYANON (Sanaga-Maritime - LITTORAL)",
  "OBALA (Lékié - CENTRE)",
  "OKOLA (Lékié - CENTRE)",
  "OLAMZE (Vallée-du-Ntem - SUD)",
  "OLANGUINA (Mefou-et-Afamba - CENTRE)",
  "OMBESSA (Mbam-et-Inoubou - CENTRE)",
  "OULI (Kadey - EST)",
  "OVENG (Dja-et-Lobo - SUD)",
  "PENKA-MICHEL (Menoua - OUEST)",
  "PETE-BANDJOUN (Koung-Khi - OUEST)",
  "PETTE (Diamaré - EXTREME-NORD)",
  "PITOA (Bénoué - NORD)",
  "POLI  (Faro - NORD)",
  "POUMA (Sanaga-Maritime - LITTORAL)",
  "REY-BOUBA (Mayo-Rey - NORD)",
  "Sa’a (Lékié - CENTRE)",
  "SALAPOUMBE (Boumba-et-Ngoko - EST)",
  "SANGMELIMA (Dja-et-Lobo - SUD)",
  "SANTA (Mezam - NORTH-WEST)",
  "SANTCHOU (Menoua - OUEST)",
  "SOA (Mefou-et-Afamba - CENTRE)",
  "SOMALOMO (Haut-Nyong - EST)",
  "SOULEDE-ROUA (Mayo-Tsanaga - EXTREME-NORD)",
  "TCHATI-BALI (Mayo-Danay- EXTREME-NORD)",
  "TCHOLIRE (Mayo-Rey - NORD)",
  "TIBATI (Djerem - ADAMAOUA)",
  "TIGNERE (Faro-et-Déo - ADAMAOUA)",
  "TIKO (Fako - SOUTH-WEST)",
  "TOKO (Ndian - SOUTH-WEST)",
  "TOKOMBERE (Mayo-Sava - EXTREME-NORD)",
  "TOMBEL (Koupé-Manengouba -  SOUTH-WEST)",
  "TONGA (Ndé - OUEST)",
  "TOUBORO (Mayo-Rey - NORD)",
  "TOULOUM (Mayo-Kani - EXTREME-NORD)",
  "TOUROUA (Bénoué - NORD)",
  "TUBAH (Mezam - NORTH-WEST)",
  "UPPER-BAYANG (Manyu - SOUTH-WEST) ",
  "WABANE (Lebialem - SOUTH-WEST)",
  "WAZA (Logone-et-Chari - EXTREME-NORD)",
  "WEST-COAST (Fako - SOUTH-WEST)",
  "WIDIKUM-BOFFE (Momo - NORTH-WEST)",
  "WINA (Mayo-Danay - EXTREME-NORD)",
  "WUM (Menchum - NORTH-WEST)",
  "YABASSI (Nkam - LITTORAL)",
  "YAGOUA (Mayo-Danay - EXTREME-NORD)",
  "Yaoundé 1er (Mfoundi - CENTRE)",
  "Yaoundé 2ème (Mfoundi - CENTRE)",
  "Yaoundé 3ème (Mfoundi - CENTRE)",
  "Yaoundé 4ème (Mfoundi - CENTRE)",
  "Yaoundé 5ème (Mfoundi - CENTRE)",
  "Yaoundé 6ème (Mfoundi - CENTRE)",
  "Yaoundé 7ème (Mfoundi - CENTRE)",
  "YINGUI (Nkam - LITTORAL)",
  "YOKADOUMA (Boumba-et-Ngoko - EST)",
  "YOKO (Mbam-et-Kim - CENTRE)",
  "ZHOA (Menchum - NORTH-WEST)",
  "ZINA (Logone-et-Chari - EXTREME-NORD)",
  "ZOETELE (Dja-et-Lobo - SUD)"
];

final List<String> birthList2 = [
  "Sélectionner",
  "DOUALA 1er (Wouri - LITTORAL)",
  "DOUAL 2ème (Wouri - LITTORAL)",
  "DOUALA 3ème (Wouri - LITTORAL)",
  "DOUALA 4ème (Wouri - LITTORAL)",
  "DOUALA 5ème (Wouri - LITTORAL)",
  "BONALEA (Moungo - LITTORAL)",
  "DOUALA 6ème (Wouri - LITTORAL)",
  "BARE-BAKEM (Moungo - LITTORAL)",
  "DIZANGUE (Sanaga-Maritime - LITTORAL)",
  "DIBAMBA (Sanaga-Maritime - LITTORAL)",
  "DIBOMBARI (Moungo - LITTORAL)",
  "DIBOMBARI (Moungo - LITTORAL)",
  "EBONE (Moungo - LITTORAL)",
  "EDEA 1er (Sanaga-Maritime - LITTORAL)",
  "EDEA 2ème (Sanaga-Maritime - LITTORAL)",
  "LOUM (Moungo - LITTORAL)",
  "MANDJO (Moungo - LITTORAL)",
  "MANDJO (Moungo - LITTORAL)",
  "MASSOCK-SONGLOULOU (Sanaga-Maritime - LITTORAL)",
  "MBANGA (Moungo - LITTORAL)",
  "MELONG (Moungo - LITTORAL)",
  "MOMBO (Moungo - LITTORAL)",
  "MOUANKO (Sanaga-Maritime - LITTORAL)",
  "NGAMBE (Sanaga-Maritime - LITTORAL)",
  "NKONDJOCK (Nkam - LITTORAL)",
  "NKONDJOCK (Nkam - LITTORAL)",
  "NKONGSAMBA 1er (Moungo - LITTORAL)",
  "NKONGSAMBA 2ème (Moungo - LITTORAL)",
  "NKONGSAMBA 3ème (Moungo - LITTORAL)",
  "NDOBIAN (Nkam - LITTORAL)",
  "NDOM (Sanaga-Maritime - LITTORAL)",
  "POUMA (Sanaga-Maritime Littoral)",
  "NGWEI (Sanaga-Maritime - LITTORAL)",
  "PENDJA (Moungo - LITTORAL)",
  "NYANON (Sanaga-Maritime - LITTORAL)",
  "YABASSI (Nkam - LITTORAL)",
  "YINGUI (Nkam -- LITTORAL)",
  "BAFOUSSAM 1er (Mifi - OUEST)",
  "BAFOUSSAM 2ème (Mifi - OUEST)",
  "BAFOUSSAM 3ème (Mifi - OUEST",
  "ANDEK (Momo - NORTH-WEST)",
  "BAFUT (Mezam - NORTH-WEST)",
  "BALI (Mezam - NORTH-WEST)",
  "BALIKUMBAT (Ngo-Ketundjia - NORTH-WEST)",
  "BAMENDA 1er (Mezam - NORTH-WEST)",
  "BAMENDA 2ème (Mezam - NORTH-WEST)",
  "BAMENDA 3ème (Mezam - NORTH-WEST)",
  "BATIBO (Momo - NORTH-WEST)",
  "BELO (Boyo - NORTH-WEST)",
  "BENAKUMA (Menchum - NORTH-WEST)",
  "ELAK-OKU (Bui - NORTH-WEST)",
  "FONFUKA (Boyo - NORTH-WEST)",
  "FONFUKA (Boyo - NORTH-WEST)",
  "JAKIRI (Bui - NORTH-WEST)",
  "NJIKWA (Momo - NORTH-WEST)",
  "NJINIKOM (Boyo - NORTH-WEST)",
  "NKAMBE (Donga-Mantung - NORTH-WEST)",
  "NKOR (Bui - NORTH-WEST)",
  "NKUM (Bui - NORTH-WEST)",
  "NWA (Donga-Mantung - NORTH-WEST)",
  "NDU (Donga-Mantung) - NORTH-WEST",
  "MBENGWI (Momo - NORTH-WEST)",
  "NDOP (Ngo-ketundjia - NORTH-WEST)",
  "KUMBO (Bui - NORTH-WEST)",
  "MBIAME (Bui - NORTH-WEST)",
  "MISAJE (Donga-Mantung - NORTH-WEST)",
  "SANTA (Mezam - NORTH-WEST)",
  "ZHOA (Menchum - NORTH-WEST)",
  "WUM (Menchum - NORTH-WEST)",
  "WIDIKUM-BOFFE (Momo - NORTH-WEST)",
  "TUBAH (Mezam - NORTH-WEST)",
  "FUNDONG (Boyo - NORTH-WEST)",
  "FURU-AWA (Menchum - NORTH-WEST)",
  "FUNDONG (Boyo - NORTH-WEST)",
  "FURU-AWA (Menchum - NORTH-WEST)",
  "AKO (Donga-Mantung - NORTH-WEST)",
  "BABESSI (Ngo-Ketundjia - NORTH-WEST)",
  "DEMBO (Bénoué - NORD)",
  "BIBEMI (Bénoué - NORD)",
  "BEKA (Faro - NORD)",
  "BARNDAKE (Bénoué - NORD)",
  "BASHEO (Bénoué - NORD)",
  "GAROUA 1er (Bénoué - NORD)",
  "GAROUA 2ème (Bénoué - NORD)",
  "GAROUA 3ème (Bénoué - NORD)",
  "GASHIGA (Bénoué - NORD)",
  "LAGDO (Bénoué - NORD)",
  "FIGUIL (Mayo-Louuti - NORD)",
  "GUIDER (Mayo-Louti - NORD)",
  "MAYO-OULO (Mayo-Louti - NORD)",
  "MADINGRING (Mayo-Rey - NORD)",
  "NGONG (Bénoué - NORD)",
  "GAROUA 1er (Bénoué - NORD)",
  "FIGUIL (Mayo-Louuti - NORD)",
  "PITOA (Bénoué - NORD)",
  "TCHOLLIRE (Mayo-Rey - NORD)",
  "POLI (Faro - NORD)",
  "REY-BOUBA (Mayo-Rey - NORD)",
  "TOUBORO (Mayo-Rey - NORD)",
  "TOUROUA (Bénoué - NORD)",
  "EKONDO-TITI (Ndian - SOUTH-WEST)",
  "EYUMODJOCK (Manyu - SOUTH-WEST)",
  "AKWAYA (Manyu - SOUTH-WEST)",
  "ALOU (Lebialem - SOUTH-WEST)",
  "BAMUSSO (Ndian - SOUTH-WEST)",
  "BANGUEM (Koupé-Manengouba - SOUTH-WEST)",
  "DIKOME-BALUE (Ndiang - SOUTH-WEST)",
  "EYUMODJOCK (Manyu - SOUTH-WEST)",
  "KOMBO-ABEDIMO (Ndian - SOUTH-WEST)",
  "KOMBO-IDINTI (Ndian - SOUTH-WEST)",
  "IDABATO (Ndian - SOUTH-WEST)",
  "ISANGUELE (Ndian - SOUTH-WEST)",
  "KONYE (Meme SOUTH-WEST)",
  "BUEA (Fako - SOUTH-WEST)",
  "KUMBA 1er (Meme - SOUTH-WEST)",
  "KUMBA 2ème (Meme - SOUTH-WEST)",
  "KUMBA 3ème (Meme - SOUTH-WEST)",
  "LIMBE 1er (Fako -SOUTH-WEST)",
  "LIMBE 2è (Fako - SOUTH-WEST)",
  "KUMBA 2ème (Meme - SOUTH-WEST)",
  "MAMFE (Manyu - SOUTH-WEST)",
  "MBONGE (Meme - SOUTH-WEST)",
  "MBONGE (Meme - SOUTH-WEST)",
  "MENJI (Lebialem - SOUTH-WEST)",
  "MUNDEMBA (Ndian - SOUTH-WEST)",
  "LIMBE 3è (Fako - SOUTH-WEST)",
  "TIKO (Fako - SOUTH-WEST)",
  "TOKO (Ndian - SOUTH-WEST)",
  "NGUTI (Koupé-Manengouba - SOUTH-WEST)",
  "WEST COAST (Fako - SOUTH-WEST)",
  "UPPER BAYANG (Manyu SOUTH-WEST)",
  "WABANE (Lebialem - SOUTH-WEST)",
  "TOMBEL (Koupé-Manengouba SOUTH-WEST)",
  "TOMBEL (Koupé-Manengouba SOUTH-WEST)",
  "AFANLOUM (Mefou-et-Afamba- CENTRE)",
  "AKOEMAN (Nyong-et-So'o - CENTRE)",
  "AKONO (Mefou-et-Akono - CENTRE)",
  "AKONOLINGA (Nyong-et-Mfoumou - CENTRE)",
  "AWAE (Mefou-et-Afamba - CENTRE)",
  "AYOS (Nyong-et-Mfoumou - CENTRE)",
  "BAFIA (Mbam-et-Inoubou - CENTRE)",
  "BIBEY (Haute-Sanaga - CENTRE)",
  "BIBEY (Haute-Sanaga - CENTRE)",
  "BIKOK (Méfou-et-Akono - CENTRE)",
  "BATCHENGA (Lékié - CENTRE)",
  "BONDJOCK (Nyong-et-Kéllé - CENTRE)",
  "BOTMAKAK (Nyong-et-Kéllé - CENTRE)",
  "BOKITO (Mbam-et-Inoubou - CENTRE)",
  "BIYOUHA (Nong-et-Kéllé CENTRE)",
  "DEUK (Mbam-et-Inoubou - CENTRE)",
  "ENDOM (Nyong-et-Mfoumou - CENTRE)",
  "ESEKA (Nyong-et-Kéllé - CENTRE)",
  "ESSE (Méfou-et-Afamba - CENTRE)",
  "EVODOULA (Lékié - CENTRE)",
  "ELIG-MFOMO (Lékié - CENTRE)",
  "ENDOM (Nyong-et-Mfoumou - CENTRE)",
  "ESEKA (Nyong-et-Kéllé - CENTRE)",
  "ESSE (Méfou-et-Afamba - CENTRE)",
  "EVODOULA (Lékié - CENTRE)",
  "YAOUNDE 1er (Mfoundi - CENTRE)",
  "YAOUNDE 2ème (Mfoundi - CENTRE)",
  "YAOUNDE 3ème (Mfoundi - CENTRE)",
  "YAOUNDE 4ème (Mfoundi - CENTRE)",
  "YAOUNDE 5ème (Mfoundi - CENTRE)",
  "YAOUNDE 6ème (Mfoundi - CENTRE)",
  "Yaoundé 7ème (Mfoundi - CENTRE)",
  "KIIKI (Mbam-et-Inoubou - CENTRE)",
  "KOBDOMBO (Nyong-et-Mfoumou - CENTRE)",
  "DIBANG (Nyong-et-Kéllé - CENTRE)",
  "EDZENDOUAN (Méfou-et-Afamba - CENTRE)",
  "DZENG (Nyong-et-So'o - CENTRE)",
  "EBEDA (Lékié - CENTRE)",
  "KON-YAMBETTA (Mbam-et-Inoubou - CENTRE)",
  "KONTCHA (Faro-et-Déo - CENTRE)",
  "MBALMAYO (Nyong-et-So'o - CENTRE)",
  "MBANDJOCK (Haute-Sanaga - CENTRE)",
  "LEMBE-YEZOUM (Haute-Sanaga - CENTRE)",
  "LOBO (Lékié - CENTRE)",
  "MAKAK (Nyong-et-Kéllé - CENTRE)",
  "MAKENENE (Mbam-et-Inoubou - CENTRE)",
  "YOKO (Mbam-et-Kim - CENTRE)",
  "YOKO (Mbam-et-Kim - CENTRE)",
  "MBANGASSINA (Mbam-et-Kim - CENTRE)",
  "MBANKOMO (Méfou-et-Akono - CENTRE)",
  "NGOG-MAPUBI (Nyong-et-Kéllé - CENTRE)",
  "NGOMEDZAP (Nyong-et-So'o - CENTRE)",
  "MONATELE (Lékié - CENTRE)",
  "MONATELE (Lékié - CENTRE)",
  "NGOUMOU (Méfou-et-Akono - CENTRE)",
  "MATOMB (Nyong-et-Kéllé - CENTRE)",
  "NITOUKOU (Mbam-et-Inoubou - CENTRE)",
  "NKOLAFAMBA (Méfou-et-Afamba - CENTRE)",
  "NGUI-BASSAL (Nyong-et-Kéllé - CENTRE)",
  "NGORO (Mbam-et-Kim - CENTRE)",
  "NKOLMETET (Nyong-et-So'o - CENTRE)",
  "NKOTENG (Haute-Sanaga - CENTRE)",
  "NGAMBE-TIKAR (Mbam-et-Kim - CENTRE)",
  "NSEM (Haute-Sanaga - CENTRE)",
  "NTUI (Mbam-et-Kim - CENTRE)",
  "OBALA (Lékié - CENTRE)",
  "OKOLA (Lékié - CENTRE)",
  "OLANGUINA (Méfou-et-Afamba - CENTRE)",
  "OMBESSA (Mbam-et-Inoubou CENTRE)",
  "SA'A (Lékié - CENTRE)",
  "SOA (Méfou-et-Afamba - CENTRE)",
  "NANGA-EBOKO (Haute-Sanaga - CENTRE)",
  "NDIKINIMEKI (Mbam-et-Inoubou - CENTRE)",
  "MENGUEME (Nyong-et-So'o - CENTRE)",
  "MESSONDO (Nyong-et-Kéllé - CENTRE)",
  "MFOU (Méfou-et-Afamba - CENTRE)",
  "MENGANG (Nyong-et-Mfoumou - CENTRE)",
  "MINTA (Haute-Sanaga - CENTRE)",
  "BABADJOU (Bamboutos - OUEST)",
  "BAFANG (Haut-Nkam - OUEST)",
  "BAHAM (Hauts-Plateaux - OUEST)",
  "BAKOU (Haut-Nkam - OUEST)",
  "BAMENDJOU (Hauts-Plateaux - OUEST)",
  "BANA (Haut-Nkam - OUEST)",
  "BANDJA (Haut-Nkam - OUEST)",
  "BANDJOUN -Koung-Khi - OUEST)",
  "BANGANTE (Ndé - OUEST)",
  "BANKA (Haut-Nkam - OUEST)",
  "BANGOU (Hauts -Plateaux - OUEST)",
  "BANGOURAIN (Noun-OUEST)",
  "BANWA (Haut-Nkam - OUEST)",
  "BANWA (Haut-Nkam - OUEST)",
  "BASSAMBA (Ndé - OUEST)",
  "BATCHAM (Bamboutos - OUEST)",
  "BATIE (Hauts-Plateaux - OUEST)",
  "BAYANGAM (Koung-Khi - OUEST)",
  "BAZOU (Ndé - OUEST)",
  "DSCHANG (Menoua - OUEST)",
  "DEMDEMG (Koung-Khi - OUEST)",
  "FOKOUE (Menoua - OUEST)",
  "FONGO-TONGO (Menoua - OUEST)",
  "FOUMBAN (Noun - OUEST)",
  "FOUMBOT (Noun - OUEST)",
  "GALIM (Bamboutos - OUEST)",
  "FOKOUE (Menoua - OUEST)",
  "FONGO-TONGO (Menoua - OUEST)",
  "FOUMBAN (Noun - OUEST)",
  "FOUMBOT (Noun - OUEST)",
  "GALIM (Bamboutos - OUEST)",
  "KEKEM (Haut-Nkam - OUEST)",
  "KEKEM (Haut-Nkam - OUEST)",
  "KOUOPTAMO (Noun - OUEST)",
  "KOUTABA (Noun - OUEST)",
  "MAGBA (Noun - OUEST)",
  "MALENTOUEN (Noun - OUEST)",
  "MASSANGAM (Noun - OUEST)",
  "MBOUDA (Bamboutos - OUEST)",
  "NKONG-ZEM (Menoua - OUEST)",
  "NJIMOM (Noun - OUEST)",
  "PENKA-MICHEL (Menoua - OUEST)",
  "PENKA-MICHEL (Menoua - OUEST)",
  "SANTCHOU (Menoua - OUEST)",
  "TONGA (Ndé - OUEST)"
];

final List<String> reasonList = [
  "CONCOURS ADMINISTRATIF AU CAMEROUN",
  "MEDAILLES",
  "CANDIDATURE AUX ELECTIONS",
  "ACCES PORTUAIRES",
  "ORGANISMES INTERNATIONAUX",
  "UTILISER HORS DU CAMEROUN",
  "RECRUTEMENT",
  "ETRANGER AYANT VECU AU CAMEROUN",
  "ETRANGER AYANT TRAVAILLE AU CAMEROUN",
  "ETRANGERS NE AU CAMEROUN",
  "CAMEROUNAIS NE A L ETRANGER",
  "CAMEROUNAIS AYANT PERDU LA NATIONALITE CAMEROUNAISE",
  "REGROUPEMNT PROFESSIONNEL",
  "CONVENANCE PERSONNELLE",
  "PROMOTION",
  "NOMINATION",
  "CONCOURS A L'ETRANGER",
  "CONCOURS D'INTEGRATION A LA FONCTION PUBLIQUE",
  "CONCOURS FORCES ARMEES, GENDARMERIE ET POLICE",
  "COMPLETER UN DOSSIER",
  "BANYO (Mayo-Banyo - ADAMAOUA)",
  "BANKIM (Mayo-Banyo - ADAMAOUA)",
  "GALIM-TIGNERE (Faro-et-Déo - ADAMAOUA)",
  "BELEL (Vina - ADAMAOUA)",
  "GALIM-TIGNERE (Faro-et-Déo - ADAMAOUA)",
  "DIR (Mbéré - ADAMAOUA)",
  "DJOHONG (Mbéré - ADAMAOUA)",
  "MEINGANGA (Mbéré - ADAMAOUA)",
  "NGANHA (Vina - ADAMAOUA)",
  "NGAOUÏ (Mbéré - ADAMAOUA)",
  "NGAOUNDAL (Djérem - ADAMAOUA)",
  "NGAOUNDERE 1er (Vina - ADAMAOUA)",
  "NGAOUNDERE 1er (Vina - ADAMAOUA)",
  "NGAOUNDERE 2ème (Vina - ADAMAOUA)",
  "NGAOUNDERE 3ème (Vina - ADAMAOUA)",
  "MAYO-BALEO (Faro-et-Déo - ADAMAOUA)",
  "MAYO-DARLE (Mayo-Banyo - ADAMAOUA)",
  "MBE (Vina - ADAMAOUA)",
  "TIBATI (Djérem - ADAMAOUA)",
  "TIGNERE (Faro-e-tDéo - ADAMAOUA)",
  "NYAMBAKA (Vina - ADAMAOUA)",
  "MARTAP (Vina - ADAMAOUA)"
];

final List<String> nationalityList = [
  "Sélectionner",
  'Afghanistan',
  'Afrique du Sud',
  'Albanie',
  'Algérie',
  'Allemagne',
  'Andorre',
  'Angola',
  'Anguilla',
  'Antarctique',
  'Antigua-et-Barbuda',
  'Antilles néerlandaises',
  'Arabie Saoudite',
  'Argentine',
  'Arménie',
  'Aruba',
  'Australie',
  'Autriche',
  'Azerbaïdjan',
  'Bahamas',
  'Bahreïn',
  'Bangladesh',
  'Barbade',
  'Belgique',
  'Belize',
  'Bermudes',
  'Bhoutan',
  'Biélorussie',
  'Bolivie',
  'Bosnie-Herzégovine',
  'Botswana',
  'Brésil',
  'Brunéi Darussalam',
  'Bulgarie',
  'Burkina Faso',
  'Burundi',
  'Cambodge',
  'Cameroun',
  'Canada',
  'Cap-Vert',
  'Chili',
  'Chine',
  'Chypre',
  'Colombie',
  'Comores',
  'Congo',
  'Corée du Nord',
  'Corée du Sud',
  'Costa Rica',
  'Côte d’Ivoire',
  'Croatie',
  'Cuba',
  'Danemark',
  'Djibouti',
  'Dominique',
  'Égypte',
  'Émirats Arabes Unis',
  'Équateur',
  'Érythrée',
  'Espagne',
  'Estonie',
  'États-Unis',
  'Éthiopie',
  'Fidji',
  'Finlande',
  'France',
  'Gabon',
  'Gambie',
  'Géorgie',
  'Géorgie du Sud et les îles Sandwich du Sud',
  'Ghana',
  'Gibraltar',
  'Grèce',
  'Grenade',
  'Groenland',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernesey',
  'Guinée',
  'Guinée équatoriale',
  'Guinée-Bissau',
  'Guyana',
  'Guyane française',
  'Haïti',
  'Honduras',
  'Hongrie',
  'Île Christmas',
  'Île de Man',
  'Île Norfolk',
  'Îles Åland',
  'Îles Caïmans',
  'Îles Cocos',
  'Îles Cook',
  'Îles Féroé',
  'Îles Malouines',
  'Îles Mariannes du Nord',
  'Îles Marshall',
  'Îles mineures éloignées des États-Unis',
  'Îles Pitcairn',
  'Îles Salomon',
  'Îles Turques-et-Caïques',
  'Îles Vierges américaines',
  'Îles Vierges britanniques',
  'Îles Wallis et Futuna',
  'Inde',
  'Indonésie',
  'Iraq',
  'Irlande',
  'Islande',
  'Israël',
  'Italie',
  'Jamaïque',
  'Japon',
  'Jersey',
  'Jordanie',
  'Kazakhstan',
  'Kenya',
  'Kirghizistan',
  'Kiribati',
  'Koweït',
  'Laos',
  'Lesotho',
  'Lettonie',
  'Liban',
  'Libéria',
  'Libye',
  'Liechtenstein',
  'Lituanie',
  'Luxembourg',
  'Macédoine',
  'Madagascar',
  'Malaisie',
  'Malawi',
  'Maldives',
  'Mali',
  'Malte',
  'Maroc',
  'Martinique',
  'Maurice',
  'Mauritanie',
  'Mayotte',
  'Mexique',
  'Moldavie',
  'Monaco',
  'Mongolie',
  'Montserrat',
  'Mozambique',
  'Namibie',
  'Nauru',
  'Népal',
  'Nicaragua',
  'Niger',
  'Nigéria',
  'Niue',
  'Norvège',
  'Nouvelle-Calédonie',
  'Nouvelle-Zélande',
  'Oman',
  'Ouganda',
  'Ouzbékistan',
  'Pakistan',
  'Palaos',
  'Panama',
  'Papouasie-Nouvelle-Guinée',
  'Paraguay',
  'Pays-Bas',
  'Pérou',
  'Philippines',
  'Pitcairn',
  'Pologne',
  'Polynésie française',
  'Porto Rico',
  'Portugal',
  'Qatar',
  'République centrafricaine',
  'République dominicaine',
  'République tchèque',
  'Réunion',
  'Roumanie',
  'Royaume-Uni',
  'Russie',
  'Rwanda',
  'Sahara occidental',
  'Saint-Barthélemy',
  'Saint-Christophe-et-Niévès',
  'Saint-Marin',
  'Saint-Martin',
  'Saint-Pierre-et-Miquelon',
  'Saint-Siège',
  'Saint-Vincent-et-les Grenadines',
  'Sainte-Hélène',
  'Sainte-Lucie',
  'Salomon',
  'Salvador',
  'Samoa',
  'Samoa américaines',
  'Sao Tomé-et-Principe',
  'Sénégal',
  'Serbie',
  'Seychelles',
  'Sierra Leone',
  'Singapour',
  'Slovaquie',
  'Slovénie',
  'Somalie',
  'Soudan',
  'Soudan du Sud',
  'Sri Lanka',
  'Suède',
  'Suisse',
  'Suriname',
  'Swaziland',
  'Syrie',
  'Tadjikistan',
  'Taïwan',
  'Tanzanie',
  'Tchad',
  'Terres australes françaises',
  'Territoire britannique de l’océan Indien',
  'Thaïlande',
  'Timor oriental',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinité-et-Tobago',
  'Tunisie',
  'Turkménistan',
  'Turquie',
  'Tuvalu',
  'Ukraine',
  'Uruguay',
  'Vanuatu',
  'Venezuela',
  'Viêt Nam',
  'Wallis-et-Futuna',
  'Yémen',
  'Zambie',
  'Zimbabwe',
];

List<String> deliveryList = [
  "J'ACCCEPTE QUE VOUS N'IREZ PAS DANS LES SOUS QUARTIER",
  "J'ACCEPTE RECEVOIR  EN ROUTE A L'AXE PRINCIPAL",
  "J'ACCEPTE RECEVOIR AU CARREFOUR",
  "J'ACCEPTE RECEVOIR AU POINT DE REPERE BIEN CONNU",
  "VOUS ALLEZ ENVOYER PAR LES KALNDOS QUI VIENNENT CHEZ MOI",
];

List<String> servicesList = [
  "OUI, JE LE SAIS",
  "JE NE SUIS PAS CONCERNE",
];

List<String> buyChoice = [
  "OUI",
  "NON",
];

List<String> allCoursList = [
  "TPGI Mfou",
  "TPGI Mbalmayo",
  "TPGI Ngoumou",
  "TPGI Akonolinga",
  "TPGI Bafia",
  "TPGI Monatélé",
  "TPGI Nanga- Eboko",
  "TPGI Eséka",
  "TPI Yaoundé- Centre- Administratif",
  "TPI Yaoundé- Ekounou",
  "TPI Yaoundé- Mendong",
  "TPGI Ntui",
  "TPGI TPGI Abong",
  "TPGI Batouri",
  "TPGI Yokadouma",
  "TPI Bertoua",
  "TPGI Kaélé",
  "TPI Maroua",
  "TPI Makary",
  "TPI Doukoula",
  "TPGI Edéa",
  "TPGI Yabassi",
  "TPI Douala- Bonanjo",
  "TPI Douala Ndonkoti",
  "TPI Douala Bonabéri",
  "TPI Mbanga",
  "TPI Nkongsamba",
  "TPGI Guider"
      "TPGI Tcholliré",
  "TPGI Poli",
  "TPI Garoua",
  "TPI Touboro",
  "TPGI Guider"
      "TPGI Tcholliré",
  "TPGI Poli",
  "TPI Garoua",
  "TPI Touboro",
  "TPGI Ndop",
  "TPGI Kumbo",
  "TPGI Mbengwi",
  "TPGI Nkambé",
  "TPGI Wum",
  "TPGI Fundung",
  "TPI Bamenda",
  "TPI Batibo",
  "TPI Bali",
  "TPGI Bafang",
  "TPGI Bagangté",
  "TPGI Dschang",
  "TPGI Mbouda",
  "TPGI Bandjoun",
  "TPGI Baham",
  "TPGI Foumban",
  "TPI Bafoussam",
  "TPI Foumbot",
  "TPGI Ambam",
  "TPGI Kribi",
  "TPGI Sangmelima",
  "TPI Ebolowa",
  "TPI Djoum",
  "TPI Bengbis",
  "TPGI Bangem",
  "TPGI Manfé",
  "TPGI Mudemba",
  "TPGI Menji",
  "TPI Buéa",
  "TPI Limbé",
  "TPI Munyuka",
  "TPI Tiko",
  "TPI Kumba",
  "TPI Tombel",
];

List<String> coursCentre1 = [
  "TPGI Mbalmayo",
  "TPGI Akonolinga",
  "TPGI Bafia",
  "TPGI Eséka",
  "TPGI Mfou",
  "TPGI Monatélé",
  "TPGI Nanga- Eboko",
  "TPGI Ngoumou",
  "TPGI Ntui",
  "TPI Yaoundé- Centre- Administratif",
  "TPI Yaoundé- Ekounou",
  "TPI Yaoundé- Mendong",
];

List<String> coursEst = [
  "TPGI TPGI Abong",
  "TPGI Batouri",
  "TPGI Yokadouma",
  "TPI Bertoua",
];

List<String> coursExtremNord = [
  "TPGI Kaélé",
  "TPI Maroua",
  "TPI Makary",
  "TPI Doukoula",
];

List<String> coursLittoral = [
  "TPGI Edéa",
  "TPGI Yabassi",
  "TPI Douala- Bonanjo",
  "TPI Douala Ndonkoti",
  "TPI Douala Bonabéri",
  "TPI Mbanga",
  "TPI Nkongsamba"
];

List<String> coursNord = [
  "TPGI Guider"
      "TPGI Tcholliré",
  "TPGI Poli",
  "TPI Garoua",
  "TPI Touboro",
];

List<String> coursNordOuest = [
  "TPGI Ndop",
  "TPGI Kumbo",
  "TPGI Mbengwi",
  "TPGI Nkambé",
  "TPGI Wum",
  "TPGI Fundung",
  "TPI Bamenda",
  "TPI Batibo",
  "TPI Bali",
];

List<String> coursOuest = [
  "TPGI Foumban",
  "TPGI Bafang",
  "TPGI Bagangté",
  "TPGI Dschang",
  "TPGI Mbouda",
  "TPGI Bandjoun",
  "TPGI Baham",
  "TPGI Foumban",
  "TPI Bafoussam",
  "TPI Foumbot",
];

List<String> coursSud = [
  "TPGI Ambam",
  "TPGI Kribi",
  "TPGI Sangmelima",
  "TPI Ebolowa",
  "TPI Djoum",
  "TPI Bengbis",
];

List<String> coursSudOuest = [
  "TPGI Bangem",
  "TPGI Manfé",
  "TPGI Mudemba",
  "TPGI Menji",
  "TPI Buéa",
  "TPI Limbé",
  "TPI Munyuka",
  "TPI Tiko",
  "TPI Kumba",
  "TPI Tombel",
];

final invoice = Invoice(
  items: [
    LineItem(
      description: 'Trésor public (timbre fiscal)',
      qte: 2,
      pu: 1500,
    ),
    // LineItem(
    //   description: 'Trésor public (timbre communal)',
    //   qte: 2,
    //   pu: 0,
    // ),
  ],
);

List<String> coursAdamaoua = [
  "TPGI Banyo",
  "TPI Ngaoundéré",
  "TPGI Meinganga",
  "TPGI Tignère",
  "TPGI Tibati",
];

List<String> regionList = [
  "Selectionner",
  "ADAMAOUA Mayo-Banyo",
  "ADAMAOUA Vina",
  "ADAMAOUA Mbéré",
  "ADAMAOUA Faro-et-Déo",
  "ADAMAOUA Djerem",
  "CENTRE Mefou-et-Afamba",
  "CENTRE Nyong-et-So'o",
  "CENTRE Mefou-et-Akono",
  "CENTRE Nyong-et-Mfoumou",
  "CENTRE Mbam-et-Inoubou",
  "CENTRE Lékié",
  "CENTRE Haute-Sanaga",
  "CENTRE Nyong-et-Kéllé",
  "CENTRE Mfoundi",
  "CENTRE Mbam-et-Kim",
  "EST Haut-Nyong",
  "EST Kadey",
  "EST Lom-et-Djérem",
  "EST Boumba-et-Ngoko",
  "EXTREME-NORD Logone-et-Chari",
  "EXTREME-NORD Diamaré",
  "EXTREME-NORD Mayo-Danay",
  "EXTREME-NORD Mayo-Kani",
  "EXTREME-NORD Mayo-Tsanaga",
  "EXTREME-NORD Mayo-Sava",
  "LITTORAL Moungo",
  "LITTORAL Sanaga-Maritime",
  "LITTORAL Wouri",
  "LITTORAL Nkam",
  "NORD Bénoué",
  "NORD Faro",
  "NORD Mayo-Louti",
  "NORD Mayo-Rey",
  "NORD-OUEST Donga-Mantung",
  "NORD-OUEST Momo",
  "NORD-OUEST Ngo-Ketundjia",
  "NORD-OUEST Mezam",
  "NORD-OUEST Menchum",
  "NORD-OUEST Boyo",
  "NORD-OUEST Bui",
  "OUEST Bamboutos",
  "OUEST Haut-Nkam",
  "OUEST Mifi",
  "OUEST Hauts-Plateaux",
  "OUEST Koung-Khi",
  "OUEST Ndé",
  "OUEST Noun",
  "OUEST Menoua",
  "SUD Océan",
  "SUD Vallée-du-Ntem",
  "SUD Dja-et-Lobo",
  "SUD Mvila",
  "SUD-OUEST Manyu",
  "SUD-OUEST Lebialem",
  "SUD-OUEST Ndian",
  "SUD-OUEST Koupé-Manengouba",
  "SUD-OUEST Fako",
  "SUD-OUEST Meme",
];

List<Map<String, dynamic>> allCours = [
  {
    'name': "ADAMAOUA Mayo-Banyo",
    'value': ["TPGI Banyo"]
  },
  {
    'name': "ADAMAOUA Vina",
    'value': ["TPI Ngaoundéré"]
  },
  {
    'name': "ADAMAOUA Mbéré",
    'value': ["TPGI Meinganga"]
  },
  {
    'name': "ADAMAOUA Faro-et-Déo",
    'value': ["TPGI Tignère"]
  },
  {
    'name': "ADAMAOUA Djerem",
    'value': ["TPGI Tibati"]
  },
  {
    'name': "CENTRE Mefou-et-Afamba",
    'value': ["TPGI Mfou"]
  },
  {
    'name': "CENTRE Nyong-et-So'o",
    'value': ["TPGI Mbalmayo"]
  },
  {
    'name': "CENTRE Mefou-et-Akono",
    'value': ["TPGI Ngoumou"]
  },
  {
    'name': "CENTRE Nyong-et-Mfoumou",
    'value': ["TPGI Akonolinga"]
  },
  {
    'name': "CENTRE Mbam-et-Inoubou",
    'value': ["TPGI Bafia"]
  },
  {
    'name': "CENTRE Lékié",
    'value': ["TPGI Monatélé"]
  },
  {
    'name': "CENTRE Haute-Sanaga",
    'value': ["TPGI Nanga- Eboko"]
  },
  {
    'name': "CENTRE Nyong-et-Kéllé",
    'value': ["TPGI Eséka"]
  },
  {
    'name': "CENTRE Mfoundi",
    'value': [
      "TPI Yaoundé- Centre Administratif",
      "TPI Yaoundé- Ekounou",
      "TPI Yaoundé- Mendong",
    ]
  },
  {
    'name': "CENTRE Mbam-et-Kim",
    'value': ["TPGI Ntui"]
  },
  {
    'name': "EST Haut-Nyong",
    'value': ["TPGI Abong-Mbang"]
  },
  {
    'name': "EST Kadey",
    'value': ["TPGI Batouri"]
  },
  {
    'name': "EST Lom-et-Djérem",
    'value': ["TPGI Bertoua 1er"]
  },
  {
    'name': "EST Boumba-et-Ngoko",
    'value': ["TPGI Yokadouma"]
  },
  {
    'name': "NORD Bénoué",
    'value': ["TPI Garoua"]
  },
  {
    'name': "NORD Faro",
    'value': ["TPGI Poli"]
  },
  {
    'name': "NORD Mayo-Louti",
    'value': ["TPGI Guider"]
  },
  {
    'name': "NORD Mayo-Rey",
    'value': ["TPGI Tcholliré", "TPI TOUBORO"]
  },
  {
    'name': "EXTREME-NORD Logone-et-Chari",
    'value': ['TPGI- KOUSSERI', 'TPI MAKARY']
  },
  {
    'name': "EXTREME-NORD Diamaré",
    'value': ['TPI-MAROUA', 'TPI NDOUKOULA']
  },
  {
    'name': "EXTREME-NORD Mayo-Danay",
    'value': ['TPGI-YAGOUA']
  },
  {
    'name': "EXTREME-NORD Mayo-Kani",
    'value': ['TPGI-KAELE']
  },
  {
    'name': "EXTREME-NORD Mayo-Tsanaga",
    'value': ['TPGI- MOKOLO']
  },
  {
    'name': "EXTREME-NORD Mayo-Sava",
    'value': ['TPGI-MORA']
  },
  {
    'name': "LITTORAL Moungo",
    'value': ['TPI-NKONGSAMBA', 'TPI-MBANGA']
  },
  {
    'name': "LITTORAL Sanaga-Maritime",
    'value': ["TPGI-EDEA 1er"]
  },
  {
    'name': "LITTORAL Wouri",
    'value': ["TPI-Douala BONANJO", "TPI-Douala NDOKOTI", "TPI-Douala-BONABERI"]
  },
  {
    'name': "LITTORAL Nkam",
    'value': ["TPGI-YABASSI"]
  },
  {
    'name': "NORD-OUEST Donga-Mantung",
    'value': ['TPGI-Nkambe']
  },
  {
    'name': "NORD-OUEST Momo",
    'value': ['TPGI-Mbengwi']
  },
  {
    'name': "NORD-OUEST Ngo-Ketundjia",
    'value': ["TPGI-Ndop"]
  },
  {
    'name': "NORD-OUEST Mezam",
    'value': ["TPI-Bamenda", "TPI-Bali"]
  },
  {
    'name': "NORD-OUEST Menchum",
    'value': ["TPGI-wum"]
  },
  {
    'name': "NORD-OUEST Boyo",
    'value': ["TPGI-Fundun"]
  },
  {
    'name': "NORD-OUEST Bui",
    'value': ["TPGI-Kumbo"]
  },
  {
    'name': "OUEST Bamboutos",
    'value': ["TPGI-Mbouda"]
  },
  {
    'name': "OUEST Haut-Nkam",
    'value': ["TPGI-Bafang"]
  },
  {
    'name': "OUEST Mifi",
    'value': ["TPI-Bafoussam"]
  },
  {
    'name': "OUEST Hauts-Plateaux",
    'value': ["TPGI-Baham"]
  },
  {
    'name': "OUEST Koung-Khi",
    'value': ["TPGI-Bandjoun"]
  },
  {
    'name': "OUEST Ndé",
    'value': ["TPGI-Bangangté"]
  },
  {
    'name': "OUEST Noun",
    'value': ["TPI-Foumbot", "TPGI-Foumban"]
  },
  {
    'name': "OUEST Menoua",
    'value': ['TPGI-Dschang']
  },
  {
    'name': "SUD Océan",
    'value': ["TPGI-Kribi"]
  },
  {
    'name': "SUD Vallée-du-Ntem",
    'value': ["TPGI- Ambam"]
  },
  {
    'name': "SUD Dja-et-Lobo",
    'value': ["TPGI-Sangmelima", "TPI-Djoum", "TPI-Bengbis"]
  },
  {
    'name': "SUD Mvila",
    'value': ["TPI-Ebolowa"]
  },
  {
    'name': "SUD-OUEST Manyu",
    'value': ["TPGI-Manfé"]
  },
  {
    'name': "SUD-OUEST Lebialem",
    'value': ["TPGI-Menji"]
  },
  {
    'name': "SUD-OUEST Ndian",
    'value': ["TPGI-Mudemba"]
  },
  {
    'name': "SUD-OUEST Koupé-Manengouba",
    'value': ["TPGI-Banguem", "TPI-Tombel"]
  },
  {
    'name': "SUD-OUEST Fako",
    'value': ["TPI-Buéa", "TPI-Muyuka", "TPI-Tiko", "TPI-Limbé"]
  },
  {
    'name': "SUD-OUEST Meme",
    'value': ["TPI-Kumba"]
  },
];

List<String> coursCentre = [
  "TPGI Mfou",
  "TPGI Mbalmayo",
  "TPGI Ngoumou",
  "TPGI Akonolinga",
  "TPGI Bafia",
  "TPGI Monatélé",
  "TPGI Nanga- Eboko",
  "TPGI Eséka",
  "TPI Yaoundé- Centre- Administratif",
  "TPI Yaoundé- Ekounou",
  "TPI Yaoundé- Mendong",
  "TPGI Ntui",
];

List<Map<String, dynamic>> priceList = [
  {'location': "Adamaoua", 'birth': "ADAMAOUA", 'price': "7500"},
  {'location': "Adamaoua", 'birth': "CENTRE", 'price': "8500"},
  {'location': "Adamaoua", 'birth': "EST", 'price': "8500"},
  {'location': "Adamaoua", 'birth': "EXTREME-NORD", 'price': "8500"},
  {'location': "Adamaoua", 'birth': "LITTORAL", 'price': "9000"},
  {'location': "Adamaoua", 'birth': "NORD", 'price': "8000"},
  {'location': "Adamaoua", 'birth': "NORD-OUEST", 'price': "8000"},
  {'location': "Adamaoua", 'birth': "OUEST", 'price': "9000"},
  {'location': "Adamaoua", 'birth': "SUD", 'price': "9500"},
  {'location': "Adamaoua", 'birth': "SUD-OUEST", 'price': "8000"},
  //CENTRE
  {'location': "Centre", 'birth': "ADAMAOUA", 'price': "8500"},
  {'location': "Centre", 'birth': "CENTRE", 'price': "7500"},
  {'location': "Centre", 'birth': "EST", 'price': "8000"},
  {'location': "Centre", 'birth': "EXTREME-NORD", 'price': "9500"},
  {'location': "Centre", 'birth': "LITTORAL", 'price': "8000"},
  {'location': "Centre", 'birth': "NORD", 'price': "9000"},
  {'location': "Centre", 'birth': "NORD-OUEST", 'price': "8000"},
  {'location': "Centre", 'birth': "OUEST", 'price': "8000"},
  {'location': "Centre", 'birth': "SUD", 'price': "8000"},
  {'location': "Centre", 'birth': "SUD-OUEST", 'price': "8000"},
  //EST
  {'location': "Est", 'birth': "ADAMAOUA", 'price': "8500"},
  {'location': "Est", 'birth': "CENTRE", 'price': "8000"},
  {'location': "Est", 'birth': "EST", 'price': "7500"},
  {'location': "Est", 'birth': "EXTREME-NORD", 'price': "8500"},
  {'location': "Est", 'birth': "LITTORAL", 'price': "9000"},
  {'location': "Est", 'birth': "NORD", 'price': "9000"},
  {'location': "Est", 'birth': "NORD-OUEST", 'price': "8000"},
  {'location': "Est", 'birth': "OUEST", 'price': "9500"},
  {'location': "Est", 'birth': "SUD", 'price': "9500"},
  {'location': "Est", 'birth': "SUD-OUEST", 'price': "8000"},
  //EST
  {'location': "EXTREME-NORD", 'birth': "ADAMAOUA", 'price': "8500"},
  {'location': "EXTREME-NORD", 'birth': "CENTRE", 'price': "9500"},
  {'location': "EXTREME-NORD", 'birth': "EST", 'price': "8500"},
  {'location': "EXTREME-NORD", 'birth': "EXTREME-NORD", 'price': "7500"},
  {'location': "EXTREME-NORD", 'birth': "LITTORAL", 'price': "10000"},
  {'location': "EXTREME-NORD", 'birth': "NORD", 'price': "8000"},
  {'location': "EXTREME-NORD", 'birth': "NORD-OUEST", 'price': "9000"},
  {'location': "EXTREME-NORD", 'birth': "OUEST", 'price': "9500"},
  {'location': "EXTREME-NORD", 'birth': "SUD", 'price': "10000"},
  {'location': "EXTREME-NORD", 'birth': "SUD-OUEST", 'price': "9000"},
  //EXTREME-NORD
  {'location': "LITTORAL", 'birth': "ADAMAOUA", 'price': "9000"},
  {'location': "LITTORAL", 'birth': "CENTRE", 'price': "8000"},
  {'location': "LITTORAL", 'birth': "EST", 'price': "9000"},
  {'location': "LITTORAL", 'birth': "EXTREME-NORD", 'price': "10000"},
  {'location': "LITTORAL", 'birth': "LITTORAL", 'price': "7500"},
  {'location': "LITTORAL", 'birth': "NORD", 'price': "8500"},
  {'location': "LITTORAL", 'birth': "NORD-OUEST", 'price': "8000"},
  {'location': "LITTORAL", 'birth': "OUEST", 'price': "8000"},
  {'location': "LITTORAL", 'birth': "SUD", 'price': "9000"},
  {'location': "LITTORAL", 'birth': "SUD-OUEST", 'price': "8000"},
  //NORD
  {'location': "NORD", 'birth': "ADAMAOUA", 'price': "8000"},
  {'location': "NORD", 'birth': "CENTRE", 'price': "9000"},
  {'location': "NORD", 'birth': "EST", 'price': "9000"},
  {'location': "NORD", 'birth': "EXTREME-NORD", 'price': "8000"},
  {'location': "NORD", 'birth': "LITTORAL", 'price': "8500"},
  {'location': "NORD", 'birth': "NORD", 'price': "7500"},
  {'location': "NORD", 'birth': "NORD-OUEST", 'price': "9000"},
  {'location': "NORD", 'birth': "OUEST", 'price': "9000"},
  {'location': "NORD", 'birth': "SUD", 'price': "9000"},
  {'location': "NORD", 'birth': "SUD-OUEST", 'price': "9000"},
  //NORD-OUEST
  {'location': "NORD-OUEST", 'birth': "ADAMAOUA", 'price': "10000"},
  {'location': "NORD-OUEST", 'birth': "CENTRE", 'price': "9000"},
  {'location': "NORD-OUEST", 'birth': "EST", 'price': "9500"},
  {'location': "NORD-OUEST", 'birth': "EXTREME-NORD", 'price': "10000"},
  {'location': "NORD-OUEST", 'birth': "LITTORAL", 'price': "8000"},
  {'location': "NORD-OUEST", 'birth': "NORD", 'price': "9500"},
  {'location': "NORD-OUEST", 'birth': "NORD-OUEST", 'price': "7500"},
  {'location': "NORD-OUEST", 'birth': "OUEST", 'price': "8000"},
  {'location': "NORD-OUEST", 'birth': "SUD", 'price': "9500"},
  {'location': "NORD-OUEST", 'birth': "SUD-OUEST", 'price': "9000"},
  //OUEST
  {'location': "OUEST", 'birth': "ADAMAOUA", 'price': "9000"},
  {'location': "OUEST", 'birth': "CENTRE", 'price': "8000"},
  {'location': "OUEST", 'birth': "EST", 'price': "9500"},
  {'location': "OUEST", 'birth': "EXTREME-NORD", 'price': "9500"},
  {'location': "OUEST", 'birth': "LITTORAL", 'price': "8000"},
  {'location': "OUEST", 'birth': "NORD", 'price': "9000"},
  {'location': "OUEST", 'birth': "NORD-OUEST", 'price': "8000"},
  {'location': "OUEST", 'birth': "OUEST", 'price': "7500"},
  {'location': "OUEST", 'birth': "SUD", 'price': "9000"},
  {'location': "OUEST", 'birth': "SUD-OUEST", 'price': "8000"},
];

const List<String> regionsCameroon = [
  "Adamaoua",
  "Centre",
  "Est",
  "Extrême-Nord",
  "Littoral",
  "Nord",
  "Nord-Ouest",
  "Ouest",
  "Sud",
  "Sud-Ouest",
];

List<Map<String, dynamic>> regionsDepartments = [
  {
    "region": "Adamaoua",
    "departments": ["Faro et Déo", "Mayo-Banyo", "Mbéré", "Vina"],
    "court": [
      "TPGI Banyo",
      "TPI Ngaoundéré",
      "TPGI Meinganga",
      "TPGI Tignère",
      "TPGI Tibati",
    ]
  },
  {
    "region": "Centre",
    "departments": [
      "Haute-Sanaga",
      "Lekié",
      "Mbam-et-Inoubou",
      "Mbam-et-Kim",
      "Méfou-et-Afamba",
      "Méfou-et-Akono",
      "Mfoundi",
      "Nyong-et-Kéllé",
      "Nyong-et-Mfoumou",
      "Nyong-et-So'o",
    ],
    "court": [
      "TPGI Mbalmayo",
      "TPGI Akonolinga",
      "TPGI Bafia",
      "TPGI Eséka",
      "TPGI Mfou",
      "TPGI Monatélé",
      "TPGI Nanga- Eboko",
      "TPGI Ngoumou",
      "TPGI Ntui",
      "TPI Yaoundé- Centre- Administratif",
      "TPI Yaoundé- Ekounou",
      "TPI Yaoundé- Mendong",
    ]
  },
  {
    "region": "Est",
    "departments": [
      "Boumba-et-Ngoko",
      "Haut-Nyong",
      "Kadey",
      "Lom-et-Djérem",
      "Djoum",
    ],
  },
  {
    "region": "Extreme-Nord",
    "departments": [
      "Diamaré",
      "Logone-et-Chari",
      "Mayo-Danay",
      "Mayo-Kani",
      "Mayo-Sava",
      "Mayo-Tsanaga",
    ],
    "court": [
      "TPGI Kaélé",
      "TPI Maroua",
      "TPI Makary",
      "TPI Doukoula",
    ]
  },
  {
    "region": "Littoral",
    "departments": ["Moungo", "Nkam", "Sanaga-Maritime", "Wouri"],
    "court": [
      "TPGI Edéa",
      "TPGI Yabassi",
      "TPI Douala- Bonanjo",
      "TPI Douala Ndonkoti",
      "TPI Douala Bonabéri",
      "TPI Mbanga",
      "TPI Nkongsamba"
    ]
  },
  {
    "region": "Nord",
    "departments": [
      "Bénoué",
      "Faro",
      "Mayo-Louti",
      "Mayo-Rey",
      "Mayo-Tsanaga",
    ],
    "court": [
      "TPGI Guider"
          "TPGI Tcholliré",
      "TPGI Poli",
      "TPI Garoua",
      "TPI Touboro",
    ]
  },
  {
    "region": "Nord-Ouest",
    "departments": [
      "Boyo",
      "Bui",
      "Donga-Mantung",
      "Menchum",
      "Mezam",
      "Momo",
      "Ngo-Ketunjia",
    ],
    "court": [
      "TPGI Ndop",
      "TPGI Kumbo",
      "TPGI Mbengwi",
      "TPGI Nkambé",
      "TPGI Wum",
      "TPGI Fundung",
      "TPI Bamenda",
      "TPI Batibo",
      "TPI Bali",
    ]
  },
  {
    "region": "Ouest",
    "departments": [
      "Bamboutos",
      "Hauts-Plateaux",
      "Koung-Khi",
      "Menoua",
      "Mifi",
      "Ndé",
    ],
    "court": [
      "TPGI Foumban",
      "TPGI Bafang",
      "TPGI Bagangté",
      "TPGI Dschang",
      "TPGI Mbouda",
      "TPGI Bandjoun",
      "TPGI Baham",
      "TPGI Foumban",
      "TPI Bafoussam",
      "TPI Foumbot",
    ]
  },
  {
    "region": "Sud",
    "departments": [
      "Dja-et-Lobo",
      "Mvila",
      "Ntem",
      "Ocean",
    ],
    "court": [
      "TPGI Ambam",
      "TPGI Kribi",
      "TPGI Sangmelima",
      "TPI Ebolowa",
      "TPI Djoum",
      "TPI Bengbis",
    ]
  },
  {
    "region": "Sud-Ouest",
    "departments": [
      "Fako",
      "Koupé-Manengouba",
      "Lebialem",
      "Manyu",
      "Meme",
      "Ndian",
    ],
    "court": [
      "TPGI Bangem",
      "TPGI Manfé",
      "TPGI Mudemba",
      "TPGI Menji",
      "TPI Buéa",
      "TPI Limbé",
      "TPI Munyuka",
      "TPI Tiko",
      "TPI Kumba",
      "TPI Tombel",
    ]
  },
];
